### PR TITLE
fix snapshot compaction

### LINKED ISSUE #647: Snapshotting abort failure
### Error

```
thread 'tokio-runtime-worker' panicked at libsql-server/src/replication/snapshot.rs:360:13:
assertion failed: frame.header().frame_no < self.last_seen_frame_no
stack backtrace:
   0:     0x56498d092a8c - std::backtrace_rs::backtrace::libunwind::trace::he43a6a3949163f8c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x56498d092a8c - std::backtrace_rs::backtrace::trace_unsynchronized::h50db52ca99f692e7
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56498d092a8c - std::sys_common::backtrace::_print_fmt::hd37d595f2ceb2d3c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x56498d092a8c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h678bbcf9da6d7d75
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x56498d0c2fcc - core::fmt::rt::Argument::fmt::h3a159adc080a6fc9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
   5:     0x56498d0c2fcc - core::fmt::write::hb8eaf5a8e45a738e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
   6:     0x56498d08ea2e - std::io::Write::write_fmt::h9663fe36b2ee08f9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
   7:     0x56498d092874 - std::sys_common::backtrace::_print::hcd4834796ee88ad2
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x56498d092874 - std::sys_common::backtrace::print::h1360e9450e4f922a
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x56498d094063 - std::panicking::default_hook::{{closure}}::h2609fa95cd5ab1f4
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
  10:     0x56498d093d7c - std::panicking::default_hook::h6d75f5747cab6e8d
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
  11:     0x56498d0945e9 - std::panicking::rust_panic_with_hook::h57e78470c47c84de
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:707:13
  12:     0x56498d0944a1 - std::panicking::begin_panic_handler::{{closure}}::h3dfd2453cf356ecb
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:597:13
  13:     0x56498d092fb6 - std::sys_common::backtrace::__rust_end_short_backtrace::hdb177d43678e4d7e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x56498d094232 - rust_begin_unwind
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
  15:     0x56498be631e3 - core::panicking::panic_fmt::hd1e971d8d7c78e0e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
  16:     0x56498be63273 - core::panicking::panic::hd907d42d09324a32
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5
  17:     0x56498c49e6d5 - sqld::replication::snapshot::LogCompactor::new::{{closure}}::hc9e663118fcb971e
  18:     0x56498c3fe79f - tokio::runtime::task::raw::poll::h8492560a7f706e9d
  19:     0x56498cff4fe6 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h6100caaa0d9ab38e
  20:     0x56498cff3949 - tokio::runtime::scheduler::multi_thread::worker::run::hf43b69d66875b8f1
  21:     0x56498d003061 - tokio::runtime::task::raw::poll::hcaec217a827ae413
  22:     0x56498cfdd2de - std::sys_common::backtrace::__rust_begin_short_backtrace::h3b521abe8cda4ece
  23:     0x56498cfde4da - core::ops::function::FnOnce::call_once{{vtable.shim}}::ha310c6691172f268
  24:     0x56498d09a7a5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::haadd4e5af2ab0d62
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2007:9
  25:     0x56498d09a7a5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he4ba1fb09c16d807
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2007:9
  26:     0x56498d09a7a5 - std::sys::unix::thread::Thread::new::thread_start::he524ecf4b47bee95
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys/unix/thread.rs:108:17
  27:     0x7f7eb0895dd4 - start_thread
  28:     0x7f7eb09179b0 - __clone3
  29:                0x0 - <unknown>
2023-11-17T20:47:42.271354Z ERROR sqld::replication::primary::logger: fatal error: failed to compact log: log compactor thread exited, exiting
```

### Reproduction

```
minio server /tmp/minio
source .env
RUST_BACKTRACE=full cargo run --release -p sqld -- --enable-namespaces --admin-listen-addr 127.0.0.1:8081 --enable-bottomless-replication --max-log-size 1
```
then run

```
git clone git@github.com:LucioFranco/sqld-stresstest
cargo run -- single-conn
```

### PR DESCRIPTION
**Pull request by MarinPostma**
This PR fixes a bug in snapshot compaction because I changed the channel type used for compaction from a 0 sized crossbeam to a 1 sized tokio channel. This created a data race in the wallog swap, and caused the compactor to crash.

I also made the log merger non-blocking, which should improve tail latencies quite significantly for large databases.

Finally, I have added extended  testing to this feature to prevent future regression.

close #647

### CODE REVIEW

File: libsql-server/src/replication/primary/logger.rs [hunk 1]
```diff
@@ -632,12 +623,18 @@ impl LogFile {
         }
 
         tracing::info!("performing log compaction");
-        let temp_log_path = path.join("temp_log");
+        // To perform the compaction, we create a new, empty file in the `to_compact` directory.
+        // We will then atomically swap that file with the current log file.
+        // I case of crash, when filling the compactor job queue, if we find that we find a log
```
Comment (LucioFranco) [inline libsql-server/src/replication/primary/logger.rs:628]:
```suggestion
        // In case of a crash, when filling the compactor job queue, if we find that we find a log
```

File: libsql-server/src/replication/snapshot.rs [hunk 2]
```diff
@@ -2,12 +2,14 @@ use std::collections::HashSet;
...
 use std::path::{Path, PathBuf};
+use std::pin::Pin;
 use std::str::FromStr;
 use std::sync::Arc;
 
-use anyhow::Context;
+use anyhow::{bail, Context};
 use bytemuck::bytes_of;
 use futures::TryStreamExt;
+use futures_core::Future;
```
Comment (LucioFranco) [inline libsql-server/src/replication/snapshot.rs:12]: future exists in `std::future::Future`.

File: libsql-server/src/replication/snapshot.rs [hunk 3]
```diff
@@ -99,57 +102,129 @@ pub async fn find_snapshot_file(
...
-                    }
+
+        let db_path = db_path.to_path_buf();
+        // We gather pending snapshots here, so new snapshots don't interfere.
+        let pending = pending_snapshots_list(&compact_queue_dir)?;
+        // FIXME(marin): we somehow need to make this code more robust. How to deal with a
+        // compaction error?
+        tokio::task::spawn(async move {
+            // process pending snapshots if any.
+            for (to_compact_file, to_compact_path) in pending {
```
Comment (LucioFranco) [inline libsql-server/src/replication/snapshot.rs:197]: We should make sure there is an info log here so we know when a certain file is starting to compact.

File: libsql-server/src/replication/snapshot.rs [hunk 4]
```diff
@@ -99,57 +102,129 @@ pub async fn find_snapshot_file(
...
-                        tracing::error!("fatal error creating snapshot: {e}");
-                        break;
-                    }
+
+        let db_path = db_path.to_path_buf();
+        // We gather pending snapshots here, so new snapshots don't interfere.
+        let pending = pending_snapshots_list(&compact_queue_dir)?;
+        // FIXME(marin): we somehow need to make this code more robust. How to deal with a
+        // compaction error?
+        tokio::task::spawn(async move {
```
Comment (LucioFranco) [inline libsql-server/src/replication/snapshot.rs:195]: Since we don't join on this task it can fail and the database will continue to run? Is this a problem? Should we be waiting for this work to complete before we return from this function?

File: libsql-server/src/replication/snapshot.rs [hunk 5]
```diff
@@ -201,17 +276,34 @@ impl SnapshotMerger {
...
         let mut snapshots = Self::init_snapshot_info_list(db_path).await?;
-        while let Some((name, size, db_page_count)) = receiver.recv().await {
-            snapshots.push((name, size));
-            if Self::should_compact(&snapshots, db_page_count) {
-                let compacted_snapshot_info =
-                    Self::merge_snapshots(&snapshots, db_path, log_id).await?;
-                snapshots.clear();
-                snapshots.push(compacted_snapshot_info);
+        let mut working = false;
+        let mut job: Pin<Box<dyn Future<Output = anyhow::Result<_>> + Sync + Send>> =
```
Comment (LucioFranco) [inline libsql-server/src/replication/snapshot.rs:280]: We can use this type https://docs.rs/tokio-util/latest/tokio_util/sync/struct.ReusableBoxFuture.html

File: libsql-server/src/replication/snapshot.rs [hunk 6]
```diff
@@ -201,17 +276,34 @@ impl SnapshotMerger {
...
+        loop {
+            tokio::select! {
+                Some((name, size, db_page_count)) = receiver.recv() => {
+                    snapshots.push((name, size));
+                    if !working && Self::should_compact(&snapshots, db_page_count) {
+                        let snapshots = std::mem::take(&mut snapshots);
+                        let fut = async move {
+                            let compacted_snapshot_info =
+                                Self::merge_snapshots(snapshots, db_path, log_id).await?;
+                            Ok(compacted_snapshot_info)
```
Comment (LucioFranco) [inline libsql-server/src/replication/snapshot.rs:291]: I think this should be spawned in the case that we somehow error out of this function/cancel out. If we spawn and cancel out the merge will continue to ensure consistency so I think its just safer to always spawn this job and just track a join handle here?

**Review by LucioFranco — DISMISSED** [review]
Looks really good my only thing I want to see changed is spawning the merge job. the rest can be done in follow ups.

File: libsql-server/src/replication/snapshot.rs (hunk 5 above)
Comment (MarinPostma) [reply libsql-server/src/replication/snapshot.rs:280]: nice!

File: libsql-server/src/replication/snapshot.rs (hunk 4 above)
Comment (MarinPostma) [reply libsql-server/src/replication/snapshot.rs:195]: This is a background job, if it exist the receiver gets dropped, and we can' send compact jobs anymore, we will know the loop exited
